name: Build Zig Qt Project

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: master

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Download Qt from Release
      run: |
        mkdir -p aarch64-linux-qt-5.15.2
        cd aarch64-linux-qt-5.15.2
        
        curl -L -o aarch64-linux-qt-5.15.2.tar.gz \
          "https://github.com/Redbeanw44602/aarch64-linux-qt-5.15.2/releases/download/5.15.2/aarch64-linux-qt-5.15.2.tar.gz"
        
        tar -xzf aarch64-linux-qt-5.15.2.tar.gz

    - name: Configure xmake
      run: |
        xmake f \
          --qt="$(pwd)/aarch64-linux-qt-5.15.2" \
          --arch=arm64-v8a \
          --build-platform=YDP02X \
          --target-channel=dev \
          --toolchain=zig \
          -m debug \
          -vD \
          --cross=aarch64-linux-gnu.2.27

    - name: Build Project
      run: xmake build -v
